# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  L_AFE:
    max_position: 0.4786020058
    min_position: -2.1291653336
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_AR:
    max_position: 1.1228739367
    min_position: -1.1167380136
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_EB:
    max_position: 2.0739420252
    min_position: -2.0984857178
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_HAA:
    max_position: 3.1354567304
    min_position: -0.3190680039
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_HFE:
    max_position: 2.6875343404
    min_position: -0.5645049299
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_HR:
    max_position: 1.4603497101
    min_position: -0.9940195505
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_KFE:
    max_position: 2.0739420252
    min_position: -0.0736310778
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_SAA:
    max_position: 3.1354567304
    min_position: -3.1415926536
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  L_SFE:
    max_position: 1.9512235622
    min_position: -1.9144080233
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_AFE:
    max_position: 2.0739420252
    min_position: -0.5031456984
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_AR:
    max_position: 1.3989904786
    min_position: -1.0246991663
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_EB:
    max_position: 2.1353012567
    min_position: -2.1291653336
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_HAA:
    #max_position: -0.3804272354
    max_position: 0.4
    min_position: -3.1415926536
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_HFE:
    max_position: 0.4
    #max_position: -0.2577087724
    min_position: -2.712078033
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_HR:
    max_position: 0.9694758579
    min_position: -1.4848934027
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_KFE:
    max_position: 0.0490873852
    min_position: -2.5280003384
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_SAA:
    min_position: -3.1415926536
    max_position: 3.1354567304
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  R_SFE:
    max_position: 1.8898643307
    min_position: -2.0371264863
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
