controller_list:
 - name: holy_joint_trajectory_action_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - R_SAA
     - R_SFE
     - R_EB
     - R_HAA
     - R_HR
     - R_HFE
     - R_KFE
     - R_AFE
     - R_AR
     - L_SAA
     - L_SFE
     - L_EB
     - L_HAA
     - L_HR
     - L_HFE
     - L_KFE
     - L_AFE
     - L_AR
